-- Catálogo central de reglas de juego (DEV/demo con créditos simulados).
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS reglas_juego (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
 codigo varchar(80) NOT NULL UNIQUE, nombre varchar(120) NOT NULL, categoria varchar(60) NOT NULL, ejemplo varchar(220) NOT NULL,
 usa_cantidad boolean NOT NULL DEFAULT false, cantidad_min integer, cantidad_max integer,
 permite_exactamente boolean NOT NULL DEFAULT true, permite_mas boolean NOT NULL DEFAULT true, permite_menos boolean NOT NULL DEFAULT true,
 mostrar_sala boolean NOT NULL DEFAULT true, mostrar_casa boolean NOT NULL DEFAULT true, activa boolean NOT NULL DEFAULT true,
 fuente_validacion varchar(20) NOT NULL DEFAULT 'RESULTADO' CHECK (fuente_validacion IN ('RESULTADO','EVENTOS','ESTADISTICAS')),
 configuracion jsonb NOT NULL DEFAULT '{}'::jsonb, orden integer NOT NULL DEFAULT 1000, creado_por uuid REFERENCES usuarios(id),
 creado_en timestamptz NOT NULL DEFAULT now(), actualizado_en timestamptz NOT NULL DEFAULT now(),
 CHECK (cantidad_min IS NULL OR cantidad_max IS NULL OR cantidad_min <= cantidad_max)
);
CREATE INDEX IF NOT EXISTS ix_reglas_juego_destino ON reglas_juego(activa, mostrar_sala, mostrar_casa, categoria);

INSERT INTO reglas_juego (codigo,nombre,categoria,ejemplo,usa_cantidad,cantidad_min,cantidad_max,permite_exactamente,permite_mas,permite_menos,mostrar_sala,mostrar_casa,activa,fuente_validacion,orden) VALUES
('R001_GANADOR_DEL_PARTIDO','Ganador del partido','Resultado','Equipo A gana',false,NULL,NULL,true,true,true,true,true,true,'RESULTADO',1),
('R002_EMPATE','Empate','Resultado','El partido termina empatado',false,NULL,NULL,true,true,true,true,true,true,'RESULTADO',2),
('R003_GANA_O_EMPATA','Gana o empata','Resultado','Equipo A gana o empata',false,NULL,NULL,true,true,true,true,true,true,'RESULTADO',3),
('R004_NO_EMPATAN','No empatan','Resultado','El partido no termina empatado',false,NULL,NULL,true,true,true,true,true,true,'RESULTADO',4),
('R005_EQUIPO_NO_PIERDE','Equipo no pierde','Resultado','Equipo A no pierde',false,NULL,NULL,true,true,true,true,true,true,'RESULTADO',5),
('R006_MARCADOR_EXACTO','Marcador exacto','Resultado','Equipo A gana 2 a 1',true,1,10,true,true,true,true,true,true,'RESULTADO',6),
('R007_EQUIPO_MARCA_O_MAS','Equipo marca o más','Goles de equipo','Equipo A marca 2 o más goles',true,1,10,true,true,true,true,true,true,'RESULTADO',7),
('R008_EQUIPO_MARCA_EXACTAMENTE','Equipo marca exactamente','Goles de equipo','Equipo A marca exactamente 2 goles',true,1,10,true,true,true,true,true,true,'RESULTADO',8),
('R009_EQUIPO_MARCA_O_MENOS','Equipo marca o menos','Goles de equipo','Equipo A marca 2 goles o menos',true,1,10,true,true,true,true,true,true,'RESULTADO',9),
('R010_EQUIPO_NO_MARCA','Equipo no marca','Goles de equipo','Equipo A no marca',false,NULL,NULL,true,true,true,true,true,true,'RESULTADO',10),
('R011_EQUIPO_MARCA','Equipo marca','Goles de equipo','Equipo A marca al menos 1 gol',false,NULL,NULL,true,true,true,true,true,true,'RESULTADO',11),
('R012_EQUIPO_MARCA_MAS_QUE_EL_RIVAL','Equipo marca más que el rival','Goles de equipo','Equipo A marca más goles que Equipo B',false,NULL,NULL,true,true,true,true,true,true,'RESULTADO',12),
('R013_EQUIPO_MARCA_IGUAL_QUE_EL_RIVAL','Equipo marca igual que el rival','Goles de equipo','Los dos equipos marcan la misma cantidad',false,NULL,NULL,true,true,true,true,true,true,'RESULTADO',13),
('R014_HAY_O_MAS_GOLES','Hay o más goles','Total de goles','Hay 4 o más goles',true,1,10,true,true,true,true,true,true,'RESULTADO',14),
('R015_HAY_EXACTAMENTE_GOLES','Hay exactamente goles','Total de goles','Hay exactamente 3 goles',true,1,10,true,true,true,true,true,true,'RESULTADO',15),
('R016_HAY_GOLES_O_MENOS','Hay goles o menos','Total de goles','Hay 2 goles o menos',true,1,10,true,true,true,true,true,true,'RESULTADO',16),
('R017_HAY_ENTRE_DOS_CANTIDADES','Hay entre dos cantidades','Total de goles','Hay entre 2 y 4 goles',true,1,10,true,true,true,true,true,true,'RESULTADO',17),
('R018_NO_HAY_GOLES','No hay goles','Total de goles','No hay goles',false,NULL,NULL,true,true,true,true,true,true,'RESULTADO',18),
('R019_HAY_AL_MENOS_UN_GOL','Hay al menos un gol','Total de goles','Hay al menos 1 gol',false,NULL,NULL,true,true,true,true,true,true,'RESULTADO',19),
('R020_LOS_DOS_EQUIPOS_MARCAN','Los dos equipos marcan','Ambos equipos','Los dos equipos marcan',false,NULL,NULL,true,true,true,true,true,true,'RESULTADO',20),
('R021_LOS_DOS_EQUIPOS_MARCAN_AL_MENOS','Los dos equipos marcan al menos','Ambos equipos','Los dos equipos marcan al menos 2 goles',true,1,10,true,true,true,true,true,true,'RESULTADO',21),
('R022_SOLO_UN_EQUIPO_MARCA','Solo un equipo marca','Ambos equipos','Solo un equipo marca',false,NULL,NULL,true,true,true,true,true,true,'RESULTADO',22),
('R023_NINGUN_EQUIPO_MARCA','Ningún equipo marca','Ambos equipos','Ningún equipo marca',false,NULL,NULL,true,true,true,true,true,true,'RESULTADO',23),
('R024_AL_MENOS_UN_EQUIPO_NO_MARCA','Al menos un equipo no marca','Ambos equipos','Al menos un equipo no marca',false,NULL,NULL,true,true,true,true,true,true,'RESULTADO',24),
('R025_GANA_POR_O_MAS_GOLES','Gana por o más goles','Diferencia','Equipo A gana por 2 o más goles',true,1,10,true,true,true,true,true,true,'RESULTADO',25),
('R026_GANA_EXACTAMENTE_POR','Gana exactamente por','Diferencia','Equipo A gana exactamente por 2 goles',true,1,10,true,true,true,true,true,true,'RESULTADO',26),
('R027_GANA_POR_O_MENOS','Gana por o menos','Diferencia','Equipo A gana por 2 goles o menos',true,1,10,true,true,true,true,true,true,'RESULTADO',27),
('R028_DIFERENCIA_EXACTA_DE_GOLES','Diferencia exacta de goles','Diferencia','La diferencia final es exactamente 2 goles',true,1,10,true,true,true,true,true,true,'RESULTADO',28),
('R029_HAY_DIFERENCIA_O_MAS','Hay diferencia o más','Diferencia','Hay 3 o más goles de diferencia',true,1,10,true,true,true,true,true,true,'RESULTADO',29),
('R030_GANA_Y_HAY_GOLES','Gana y hay goles','Combinadas','Equipo A gana y hay 3 o más goles',true,1,10,true,true,true,true,true,true,'RESULTADO',30),
('R031_GANA_Y_LOS_DOS_MARCAN','Gana y los dos marcan','Combinadas','Equipo A gana y los dos equipos marcan',false,NULL,NULL,true,true,true,true,true,true,'RESULTADO',31),
('R032_GANA_Y_RIVAL_NO_MARCA','Gana y rival no marca','Combinadas','Equipo A gana sin recibir goles',false,NULL,NULL,true,true,true,true,true,true,'RESULTADO',32),
('R033_GANA_Y_MARCA_CANTIDAD','Gana y marca cantidad','Combinadas','Equipo A gana y marca 2 o más goles',true,1,10,true,true,true,true,true,true,'RESULTADO',33),
('R034_NO_PIERDE_Y_MARCA_CANTIDAD','No pierde y marca cantidad','Combinadas','Equipo A no pierde y marca 2 o más goles',true,1,10,true,true,true,true,true,true,'RESULTADO',34),
('R035_EMPATE_Y_LOS_DOS_MARCAN','Empate y los dos marcan','Combinadas','Empatan y los dos equipos marcan',false,NULL,NULL,true,true,true,true,true,true,'RESULTADO',35),
('R036_EMPATE_Y_HAY_GOLES','Empate y hay goles','Combinadas','Empatan y hay 2 o más goles',true,1,10,true,true,true,true,true,true,'RESULTADO',36),
('R037_LOS_DOS_MARCAN_Y_HAY_GOLES','Los dos marcan y hay goles','Combinadas','Los dos equipos marcan y hay 3 o más goles',true,1,10,true,true,true,true,true,true,'RESULTADO',37),
('R038_GANA_POR_DIFERENCIA_Y_HAY_GOLES','Gana por diferencia y hay goles','Combinadas','Equipo A gana por 2 o más y hay 3 o más goles',true,1,10,true,true,true,true,true,true,'RESULTADO',38),
('R039_EQUIPO_MARCA_Y_RIVAL_NO_MARCA','Equipo marca y rival no marca','Combinadas','Equipo A marca y Equipo B no marca',false,NULL,NULL,true,true,true,true,true,true,'RESULTADO',39),
('R040_GANA_EL_PRIMER_TIEMPO','Gana el primer tiempo','Primer tiempo','Equipo A gana el primer tiempo',false,NULL,NULL,true,true,true,true,true,true,'EVENTOS',40),
('R041_EMPATE_AL_DESCANSO','Empate al descanso','Primer tiempo','El primer tiempo termina empatado',false,NULL,NULL,true,true,true,true,true,true,'EVENTOS',41),
('R042_HAY_GOLES_EN_EL_PRIMER_TIEMPO','Hay goles en el primer tiempo','Primer tiempo','Hay 2 o más goles en el primer tiempo',true,1,10,true,true,true,true,true,true,'EVENTOS',42),
('R043_EQUIPO_MARCA_EN_EL_PRIMER_TIEMPO','Equipo marca en el primer tiempo','Primer tiempo','Equipo A marca en el primer tiempo',false,NULL,NULL,true,true,true,true,true,true,'EVENTOS',43),
('R044_EQUIPO_MARCA_CANTIDAD_EN_PRIMER_TIEMPO','Equipo marca cantidad en primer tiempo','Primer tiempo','Equipo A marca 2 o más goles en el primer tiempo',true,1,10,true,true,true,true,true,true,'EVENTOS',44),
('R045_LOS_DOS_MARCAN_EN_EL_PRIMER_TIEMPO','Los dos marcan en el primer tiempo','Primer tiempo','Los dos equipos marcan en el primer tiempo',false,NULL,NULL,true,true,true,true,true,true,'EVENTOS',45),
('R046_NO_HAY_GOLES_EN_PRIMER_TIEMPO','No hay goles en primer tiempo','Primer tiempo','No hay goles en el primer tiempo',false,NULL,NULL,true,true,true,true,true,true,'EVENTOS',46),
('R047_GANA_EL_SEGUNDO_TIEMPO','Gana el segundo tiempo','Segundo tiempo','Equipo A gana el segundo tiempo',false,NULL,NULL,true,true,true,true,true,true,'EVENTOS',47),
('R048_EMPATE_EN_EL_SEGUNDO_TIEMPO','Empate en el segundo tiempo','Segundo tiempo','El segundo tiempo termina empatado',false,NULL,NULL,true,true,true,true,true,true,'EVENTOS',48),
('R049_HAY_GOLES_EN_EL_SEGUNDO_TIEMPO','Hay goles en el segundo tiempo','Segundo tiempo','Hay 2 o más goles en el segundo tiempo',true,1,10,true,true,true,true,true,true,'EVENTOS',49),
('R050_EQUIPO_MARCA_EN_EL_SEGUNDO_TIEMPO','Equipo marca en el segundo tiempo','Segundo tiempo','Equipo A marca en el segundo tiempo',false,NULL,NULL,true,true,true,true,true,true,'EVENTOS',50),
('R051_MARCA_EN_LOS_DOS_TIEMPOS','Marca en los dos tiempos','Segundo tiempo','Equipo A marca en los dos tiempos',false,NULL,NULL,true,true,true,true,true,true,'EVENTOS',51),
('R052_HAY_GOLES_EN_LOS_DOS_TIEMPOS','Hay goles en los dos tiempos','Segundo tiempo','Hay goles en los dos tiempos',false,NULL,NULL,true,true,true,true,true,true,'EVENTOS',52),
('R053_MARCA_PRIMERO','Marca primero','Eventos','Equipo A marca primero',false,NULL,NULL,true,true,true,true,true,true,'EVENTOS',53),
('R054_MARCA_ULTIMO','Marca último','Eventos','Equipo A marca el último gol',false,NULL,NULL,true,true,true,true,true,true,'EVENTOS',54),
('R055_GOL_ANTES_DEL_MINUTO','Gol antes del minuto','Eventos','Hay un gol antes del minuto 30',true,1,10,true,true,true,true,true,true,'EVENTOS',55),
('R056_GOL_DESPUES_DEL_MINUTO','Gol después del minuto','Eventos','Hay un gol después del minuto 75',true,1,10,true,true,true,true,true,true,'EVENTOS',56),
('R057_GOL_ENTRE_MINUTOS','Gol entre minutos','Eventos','Hay un gol entre el minuto 60 y 75',true,1,10,true,true,true,true,true,true,'EVENTOS',57),
('R058_EQUIPO_MARCA_ANTES_DEL_MINUTO','Equipo marca antes del minuto','Eventos','Equipo A marca antes del minuto 30',true,1,10,true,true,true,true,true,true,'EVENTOS',58),
('R059_EQUIPO_MARCA_DESPUES_DEL_MINUTO','Equipo marca después del minuto','Eventos','Equipo A marca después del minuto 75',true,1,10,true,true,true,true,true,true,'EVENTOS',59),
('R060_EQUIPO_REMONTA','Equipo remonta','Eventos','Equipo A va perdiendo y termina ganando',false,NULL,NULL,true,true,true,true,true,true,'EVENTOS',60),
('R061_EQUIPO_RECIBE_TARJETA','Equipo recibe tarjeta','Tarjetas','Equipo A recibe al menos 1 tarjeta',false,NULL,NULL,true,true,true,true,true,true,'ESTADISTICAS',61),
('R062_EQUIPO_RECIBE_O_MAS_TARJETAS','Equipo recibe o más tarjetas','Tarjetas','Equipo A recibe 3 o más tarjetas',true,1,10,true,true,true,true,true,true,'ESTADISTICAS',62),
('R063_HAY_O_MAS_TARJETAS','Hay o más tarjetas','Tarjetas','Hay 5 o más tarjetas',true,1,10,true,true,true,true,true,true,'ESTADISTICAS',63),
('R064_EQUIPO_RECIBE_MAS_TARJETAS','Equipo recibe más tarjetas','Tarjetas','Equipo A recibe más tarjetas que Equipo B',false,NULL,NULL,true,true,true,true,true,true,'ESTADISTICAS',64),
('R065_LOS_DOS_RECIBEN_TARJETA','Los dos reciben tarjeta','Tarjetas','Los dos equipos reciben al menos 1 tarjeta',false,NULL,NULL,true,true,true,true,true,true,'ESTADISTICAS',65),
('R066_HAY_TARJETA_ROJA','Hay tarjeta roja','Tarjetas','Hay al menos 1 tarjeta roja',false,NULL,NULL,true,true,true,true,true,true,'ESTADISTICAS',66),
('R067_EQUIPO_RECIBE_ROJA','Equipo recibe roja','Tarjetas','Equipo A recibe una tarjeta roja',false,NULL,NULL,true,true,true,true,true,true,'ESTADISTICAS',67),
('R068_HAY_O_MAS_CORNERS','Hay o más córners','Córners','Hay 9 o más córners',true,1,10,true,true,true,true,true,true,'ESTADISTICAS',68),
('R069_HAY_CORNERS_O_MENOS','Hay córners o menos','Córners','Hay 8 córners o menos',true,1,10,true,true,true,true,true,true,'ESTADISTICAS',69),
('R070_EQUIPO_CONSIGUE_O_MAS_CORNERS','Equipo consigue o más córners','Córners','Equipo A consigue 5 o más córners',true,1,10,true,true,true,true,true,true,'ESTADISTICAS',70),
('R071_EQUIPO_CONSIGUE_MAS_CORNERS','Equipo consigue más córners','Córners','Equipo A consigue más córners que Equipo B',false,NULL,NULL,true,true,true,true,true,true,'ESTADISTICAS',71),
('R072_HAY_EXACTAMENTE_CORNERS','Hay exactamente córners','Córners','Hay exactamente 10 córners',true,1,10,true,true,true,true,true,true,'ESTADISTICAS',72),
('R073_LOS_DOS_CONSIGUEN_CORNERS','Los dos consiguen córners','Córners','Los dos equipos consiguen 3 o más córners',true,1,10,true,true,true,true,true,true,'ESTADISTICAS',73),
('R074_EQUIPO_TIENE_O_MAS_TIROS','Equipo tiene o más tiros','Estadísticas','Equipo A tiene 10 o más tiros',true,1,10,true,true,true,true,true,true,'ESTADISTICAS',74),
('R075_EQUIPO_TIENE_O_MAS_TIROS_AL_ARCO','Equipo tiene o más tiros al arco','Estadísticas','Equipo A tiene 5 o más tiros al arco',true,1,10,true,true,true,true,true,true,'ESTADISTICAS',75),
('R076_EQUIPO_TIENE_MAS_TIROS','Equipo tiene más tiros','Estadísticas','Equipo A tiene más tiros que Equipo B',false,NULL,NULL,true,true,true,true,true,true,'ESTADISTICAS',76),
('R077_EQUIPO_TIENE_MAS_POSESION','Equipo tiene más posesión','Estadísticas','Equipo A tiene más posesión que Equipo B',false,NULL,NULL,true,true,true,true,true,true,'ESTADISTICAS',77),
('R078_EQUIPO_COMETE_O_MAS_FALTAS','Equipo comete o más faltas','Estadísticas','Equipo A comete 10 o más faltas',true,1,10,true,true,true,true,true,true,'ESTADISTICAS',78),
('R079_EQUIPO_TIENE_O_MAS_FUERA_DE_JUEGO','Equipo tiene o más fuera de juego','Estadísticas','Equipo A tiene 3 o más fuera de juego',true,1,10,true,true,true,true,true,true,'ESTADISTICAS',79)
ON CONFLICT (codigo) DO UPDATE SET nombre=EXCLUDED.nombre,categoria=EXCLUDED.categoria,ejemplo=EXCLUDED.ejemplo,usa_cantidad=EXCLUDED.usa_cantidad,fuente_validacion=EXCLUDED.fuente_validacion,orden=EXCLUDED.orden;
